import Head from "next/head";
import Image from "next/image";
import MainLayout from "@layout/MainLayout";
import styles from "../styles/Home.module.css";
import Carousel from "@components/Carousel";
import Intro from "./intro";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout>
        <Intro />
      </MainLayout>
    </div>
  );
}
